import type { QuestTemplate } from "./types.js";

/**
 * PROVISIONAL quest templates. Enough to exercise the scheduler and to show the shape.
 * The full, cited catalogue comes from docs/research/training-science.md and will replace this file's
 * contents; the structure stays. Every template carries its evidence tier and a citation key.
 */
export const QUEST_TEMPLATES: readonly QuestTemplate[] = [
  // The Wilds — movement
  {
    id: "wilds.steps.1",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "B",
    title: "Average 7,000 steps a day",
    gameTitle: "Wilds I: Find your stride",
    why: "Mortality risk falls steeply up to roughly 7,000–8,000 steps a day; the first thousands matter most.",
    criterion: { kind: "daily_average", metric: "steps_day", op: ">=", target: 7000 },
    windowDays: 7,
    citation: "steps.paluch2022",
    tags: [],
  },
  {
    id: "wilds.steps.2",
    region: "wilds",
    stat: "movement",
    difficulty: 2,
    evidence: "B",
    title: "Average 9,000 steps a day",
    gameTitle: "Wilds II: Longer paths",
    why: "Benefits keep accruing into the 8,000–10,000 range for adults under 60.",
    criterion: { kind: "daily_average", metric: "steps_day", op: ">=", target: 9000 },
    windowDays: 7,
    citation: "steps.paluch2022",
    tags: [],
  },
  {
    id: "wilds.breaks.1",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "C",
    title: "Break up sitting on 5 days",
    gameTitle: "Wilds I: Never still",
    why: "Interrupting prolonged sitting improves post-meal glucose and blood pressure in trials.",
    criterion: { kind: "days_meeting", metric: "sedentary_break_count_day", op: ">=", threshold: 8, days: 5 },
    windowDays: 7,
    citation: "sedentary.dunstan",
    tags: [],
  },
  // The Forge — strength
  {
    id: "forge.sessions.1",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "A",
    title: "Do 2 strength sessions this week",
    gameTitle: "Forge I: Temper the base",
    why: "Major guidelines recommend muscle-strengthening on at least two days a week.",
    criterion: { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 20 },
    windowDays: 7,
    citation: "who2020.strength",
    tags: ["load"],
  },
  {
    id: "forge.sessions.2",
    region: "forge",
    stat: "strength",
    difficulty: 2,
    evidence: "B",
    title: "Do 3 strength sessions this week",
    gameTitle: "Forge II: Heat and hammer",
    why: "Higher weekly set volume per muscle produces more growth up to a point; three sessions spread it sensibly.",
    criterion: { kind: "sessions", sessionType: "resistance", count: 3, minMinutes: 30 },
    windowDays: 7,
    citation: "volume.schoenfeld",
    tags: ["load"],
  },
  {
    id: "forge.test.grip",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "A",
    title: "Record a grip-strength test",
    gameTitle: "Forge I: Measure the iron",
    why: "Grip strength is one of the best-normed strength measures and predicts long-term health.",
    criterion: { kind: "measurement_exists", metric: "grip_kg" },
    windowDays: 14,
    citation: "grip.leong2015",
    tags: ["test"],
  },
  {
    id: "forge.test.pushups",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "B",
    title: "Record a max push-up test",
    gameTitle: "Forge I: Count the strikes",
    why: "Push-up capacity has published norms and tracks upper-body endurance.",
    criterion: { kind: "measurement_exists", metric: "pushups_max" },
    windowDays: 14,
    citation: "pushups.yang2019",
    tags: ["test"],
  },
  // The Engine — aerobic
  {
    id: "engine.zone2.1",
    region: "engine",
    stat: "aerobic",
    difficulty: 1,
    evidence: "A",
    title: "Two easy cardio sessions of 30+ minutes",
    gameTitle: "Engine I: Light the boiler",
    why: "150+ minutes of moderate aerobic activity a week is the guideline floor; easy sessions build the base.",
    criterion: { kind: "sessions", sessionType: "zone2", count: 2, minMinutes: 30 },
    windowDays: 7,
    citation: "who2020.aerobic",
    tags: ["load"],
  },
  {
    id: "engine.intervals.1",
    region: "engine",
    stat: "aerobic",
    difficulty: 2,
    evidence: "B",
    title: "One interval session (4 × 4 minutes hard)",
    gameTitle: "Engine II: Open the throttle",
    why: "4×4-minute intervals raised VO₂max more than moderate continuous training in randomised trials.",
    criterion: { kind: "sessions", sessionType: "intervals", count: 1, minMinutes: 25 },
    windowDays: 7,
    citation: "intervals.helgerud2007",
    tags: ["load"],
  },
  {
    id: "engine.test.vo2",
    region: "engine",
    stat: "aerobic",
    difficulty: 1,
    evidence: "B",
    title: "Get a VO₂max estimate",
    gameTitle: "Engine I: Read the gauge",
    why: "Cardiorespiratory fitness is among the strongest predictors of longevity; a device estimate or a field test reveals your Aerobic stat.",
    criterion: { kind: "measurement_exists", metric: "vo2max" },
    windowDays: 14,
    citation: "crf.mandsager2018",
    tags: ["test", "import"],
  },
  // Temple of Motion — mobility
  {
    id: "temple.sessions.1",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "B",
    title: "Three 10-minute mobility sessions",
    gameTitle: "Temple I: Enter the stillness",
    why: "Range of motion improves with regular stretching; total weekly time matters more than any single session.",
    criterion: { kind: "sessions", sessionType: "mobility", count: 3, minMinutes: 10 },
    windowDays: 7,
    citation: "rom.thomas2018",
    tags: [],
  },
  {
    id: "temple.test.reach",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "C",
    title: "Record a sit-and-reach test",
    gameTitle: "Temple I: Reach the floor",
    why: "A simple normed test for hamstring and lower-back range.",
    criterion: { kind: "measurement_exists", metric: "sit_and_reach_cm" },
    windowDays: 14,
    citation: "mobility.acsm",
    tags: ["test"],
  },
  // The Garden — nutrition (additive by default)
  {
    id: "garden.protein.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 1,
    evidence: "B",
    title: "Hit 1.6 g/kg protein on 5 days",
    gameTitle: "Garden I: Feed the roots",
    why: "Lean-mass gains from resistance training plateau around 1.6 g/kg/day of protein.",
    criterion: { kind: "days_meeting", metric: "protein_g_per_kg_day", op: ">=", threshold: 1.6, days: 5 },
    windowDays: 7,
    citation: "protein.morton2018",
    tags: ["additive_nutrition"],
  },
  {
    id: "garden.fiber.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 1,
    evidence: "A",
    title: "Average 25 g of fiber a day",
    gameTitle: "Garden I: Let it grow",
    why: "Dietary guidelines put adult fiber targets at 25–38 g/day; most people eat half that.",
    criterion: { kind: "daily_average", metric: "fiber_g_day", op: ">=", target: 25 },
    windowDays: 7,
    citation: "fiber.guidelines",
    tags: ["additive_nutrition"],
  },
  // The Sanctum — recovery
  {
    id: "sanctum.sleep.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 1,
    evidence: "A",
    title: "Sleep 7+ hours on 5 nights",
    gameTitle: "Sanctum I: Keep the vigil",
    why: "Adults should regularly sleep seven or more hours per night for optimal health.",
    criterion: { kind: "days_meeting", metric: "sleep_duration_h", op: ">=", threshold: 7, days: 5 },
    windowDays: 7,
    citation: "sleep.aasm2015",
    tags: ["recovery"],
  },
  {
    id: "sanctum.regular.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 2,
    evidence: "C",
    title: "Keep bedtime within an hour on 6 nights",
    gameTitle: "Sanctum II: Same hour, same door",
    why: "Sleep regularity predicts mortality risk independently of duration in large cohorts.",
    criterion: { kind: "daily_average", metric: "sleep_regularity_index", op: ">=", target: 80 },
    windowDays: 7,
    citation: "sleep.windred2023",
    tags: ["recovery"],
  },
  // The Arena — power (gated)
  {
    id: "arena.test.jump",
    region: "arena",
    stat: "power",
    difficulty: 1,
    evidence: "C",
    title: "Record a vertical jump",
    gameTitle: "Arena I: Leave the ground",
    why: "Jump height is the simplest field measure of lower-body power, which declines faster than strength with age.",
    criterion: { kind: "measurement_exists", metric: "vertical_jump_cm" },
    windowDays: 14,
    citation: "power.aging",
    tags: ["test"],
  },
];

export function templateById(id: string): QuestTemplate | undefined {
  return QUEST_TEMPLATES.find((t) => t.id === id);
}
