import type { QuestTemplate } from "./types.js";

/**
 * Quest catalogue, transcribed from the quest tables in docs/research/training-science.md and the
 * test protocols in docs/research/normative-data.md. Every template carries its evidence tier and a
 * citation key; CITATIONS resolves each key to numbered entries in a research report's Sources list.
 *
 * Copy rules the templates follow (training-science.md "Implications", 3): say "easy aerobic", not
 * "Zone 2"; say "near failure", not "to failure"; never promise lifespan years; C-tier text says
 * "linked to", never "proven to".
 *
 * Deliberately NOT transcribed yet, because the engine cannot verify them honestly:
 * forge.sets.1/2 (per-muscle set logging), wilds.green.1 (needs a GPS "outdoor" flag),
 * sanctum.hrv.guided (readiness-swap adherence), summit.balance.1 and summit.separate.1 (meta rules).
 */
export const QUEST_TEMPLATES_VERSION = "2026.10.02";

export type CitationDoc = "training-science" | "normative-data" | "design";

export interface CitationRef {
  /** Research report under docs/research whose Sources list the numbers index. */
  readonly doc: CitationDoc;
  /** Numbered entries in that Sources list. Empty for consensus values and design choices. */
  readonly sources: readonly number[];
  readonly note?: string;
}

export const CITATIONS = {
  "who2020.activity": { doc: "training-science", sources: [3] },
  "strength.pelland2025": { doc: "training-science", sources: [1] },
  "strength.near_failure": { doc: "training-science", sources: [1, 2] },
  "strength.liftmor2018": {
    doc: "training-science",
    sources: [5],
    note: "postmenopausal women with low bone mass",
  },
  "strength.deload": { doc: "training-science", sources: [6, 7] },
  "aerobic.easy_first": { doc: "training-science", sources: [9, 10] },
  "aerobic.rosenblat2025": { doc: "training-science", sources: [9] },
  "aerobic.hiit_vo2max": { doc: "training-science", sources: [12, 13] },
  "aerobic.milanovic2015": { doc: "training-science", sources: [13] },
  "aerobic.billat": { doc: "training-science", sources: [14] },
  "aerobic.crf_mortality": { doc: "training-science", sources: [15, 16], note: "association, not causation" },
  "mobility.stretch_dose": { doc: "training-science", sources: [17, 18] },
  "mobility.thomas2018": { doc: "training-science", sources: [17] },
  "mobility.dose2024": { doc: "training-science", sources: [18] },
  "mobility.behm2016": { doc: "training-science", sources: [19] },
  "mobility.afonso2021": { doc: "training-science", sources: [20] },
  "balance.falls": { doc: "training-science", sources: [3, 23] },
  "power.reid2012": { doc: "training-science", sources: [24] },
  "power.plyo_older2019": { doc: "training-science", sources: [25] },
  "power.older_adults": { doc: "training-science", sources: [24, 25] },
  "steps.dose_response": { doc: "training-science", sources: [26, 27] },
  "steps.paluch2022": { doc: "training-science", sources: [26] },
  "steps.ding2025": { doc: "training-science", sources: [27] },
  "sedentary.dunstan2012": {
    doc: "training-science",
    sources: [28],
    note: "acute trial outcomes (glucose, insulin)",
  },
  "vilpa.stamatakis": { doc: "training-science", sources: [29, 30], note: "association, not causation" },
  "protein.morton2018": { doc: "training-science", sources: [8] },
  "protein.schoenfeld2018": { doc: "training-science", sources: [32] },
  "fiber.reynolds2019": { doc: "training-science", sources: [33] },
  "plants.reynolds_predimed": { doc: "training-science", sources: [33, 34] },
  "upf.hall2019": { doc: "training-science", sources: [35] },
  "alcohol.no_safe_level": { doc: "training-science", sources: [36, 37] },
  "alcohol.hrv.pietila2018": { doc: "training-science", sources: [46] },
  "creatine.issn2017": { doc: "training-science", sources: [41] },
  "sleep.consensus_7h": {
    doc: "training-science",
    sources: [],
    note: "AASM/SRS consensus value; primary source not yet fetched (unverified)",
  },
  "sleep.windred2024": { doc: "training-science", sources: [45] },
  "sleep.windred2024.sri80": { doc: "training-science", sources: [45], note: "SRI ≥ 80 cut-off unverified" },
  "sleep.mah2011": { doc: "training-science", sources: [44], note: "single small study (n = 11 athletes)" },
  "sauna.laukkanen2015": { doc: "training-science", sources: [47] },
  "hrv.personal_baseline": { doc: "training-science", sources: [50] },
  "norms.vo2max": { doc: "normative-data", sources: [1] },
  "norms.grip": { doc: "normative-data", sources: [9] },
  "norms.pushups": {
    doc: "normative-data",
    sources: [11, 12],
    note: "percentile tables have murky provenance",
  },
  "norms.sit_to_stand": { doc: "normative-data", sources: [14] },
  "norms.vertical_jump": { doc: "normative-data", sources: [17] },
  "norms.sit_and_reach": { doc: "normative-data", sources: [19] },
  "norms.knee_to_wall": { doc: "normative-data", sources: [20] },
  "norms.single_leg_balance": { doc: "normative-data", sources: [21] },
  "norms.gap.broad_jump": {
    doc: "normative-data",
    sources: [],
    note: "no open adult norms; criterion use only",
  },
  "norms.gap.sprint": {
    doc: "normative-data",
    sources: [],
    note: "no open adult norms; phone timing unvalidated",
  },
  "design.hill_sprints": { doc: "design", sources: [], note: "design choice, protocol untested" },
  "design.food_log": {
    doc: "design",
    sources: [],
    note: "data-collection quest, not a health recommendation",
  },
} as const satisfies Record<string, CitationRef>;

export type CitationKey = keyof typeof CITATIONS;

type CitedTemplate = Omit<QuestTemplate, "citation"> & { readonly citation: CitationKey };

const TEMPLATES: readonly CitedTemplate[] = [
  // ─── The Forge — strength ───────────────────────────────────────────────────────────────────
  {
    id: "forge.sessions.1",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "A",
    title: "Do 2 strength sessions this week",
    gameTitle: "Forge I: Temper the base",
    why: "WHO recommends muscle-strengthening activity on two or more days a week for all adults.",
    criterion: { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 20 },
    windowDays: 7,
    citation: "who2020.activity",
    tags: ["load"],
  },
  {
    id: "forge.bodyweight.1",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "B",
    title: "Two bodyweight circuits, stopping 1–3 reps short of failure",
    gameTitle: "Forge I: Hammer, not shatter",
    why: "Sets taken near failure build strength and muscle; stopping 1–3 reps short gives most of the benefit with less fatigue.",
    criterion: { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 15 },
    windowDays: 7,
    citation: "strength.near_failure",
    tags: ["load"],
  },
  {
    id: "forge.sessions.2",
    region: "forge",
    stat: "strength",
    difficulty: 2,
    evidence: "B",
    title: "Do 3 strength sessions this week",
    gameTitle: "Forge II: Heat and hammer",
    why: "More hard sets per muscle each week produce more growth, with diminishing returns; three sessions spread the dose sensibly.",
    criterion: { kind: "sessions", sessionType: "resistance", count: 3, minMinutes: 30 },
    windowDays: 7,
    citation: "strength.pelland2025",
    tags: ["load"],
  },
  {
    id: "forge.test.grip",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "C",
    title: "Record a grip-strength test",
    gameTitle: "Forge I: Measure the iron",
    why: "Grip strength has the best population norms of any strength test and is linked to long-term health.",
    criterion: { kind: "measurement_exists", metric: "grip_kg" },
    windowDays: 14,
    citation: "norms.grip",
    tags: ["test"],
  },
  {
    id: "forge.test.pushups",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "C",
    title: "Log a strict max push-up test",
    gameTitle: "Forge I: Count the strikes",
    why: "Push-up capacity tracks upper-body endurance; in one cohort of firefighters, more than 40 was linked to far fewer heart events.",
    criterion: { kind: "measurement_exists", metric: "pushups_max" },
    windowDays: 14,
    citation: "norms.pushups",
    tags: ["test"],
  },
  {
    id: "forge.test.sts",
    region: "forge",
    stat: "strength",
    difficulty: 1,
    evidence: "C",
    title: "Take the 30-second sit-to-stand test",
    gameTitle: "Forge I: Rise thirty times",
    why: "The chair-stand test has published norms from age 60 and needs nothing but a chair and a timer.",
    criterion: { kind: "measurement_exists", metric: "sit_to_stand_30s" },
    windowDays: 14,
    citation: "norms.sit_to_stand",
    tags: ["test"],
    minAge: 40,
  },
  {
    id: "forge.improve.1",
    region: "forge",
    stat: "strength",
    difficulty: 3,
    evidence: "B",
    title: "Raise your estimated squat 1RM by 0.05 × bodyweight in 4 weeks",
    gameTitle: "Forge III: Forge a heavier blade",
    why: "Strength keeps responding to progressive overload; a small, logged increase in estimated 1RM is the honest marker.",
    criterion: { kind: "improve", metric: "squat_1rm_ratio", delta: 0.05 },
    windowDays: 28,
    citation: "strength.pelland2025",
    tags: [],
  },
  {
    id: "forge.bone.1",
    region: "forge",
    stat: "strength",
    difficulty: 3,
    evidence: "B",
    title: "Two sessions with heavy compound lifts (5 reps or fewer, 1–3 reps in reserve)",
    gameTitle: "Forge III: Iron in the bone",
    why: "Supervised heavy lifting improved bone density in postmenopausal women with low bone mass in the LIFTMOR trial. A choice, not a default; it needs sound technique.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 30 },
        { kind: "self_report", count: 2 },
      ],
    },
    windowDays: 7,
    citation: "strength.liftmor2018",
    tags: ["load", "opt_in"],
    minAge: 40,
  },

  // ─── The Engine — aerobic ──────────────────────────────────────────────────────────────────
  {
    id: "engine.mvpa.1",
    region: "engine",
    stat: "aerobic",
    difficulty: 1,
    evidence: "A",
    title: "Reach 150 active minutes this week",
    gameTitle: "Engine I: Light the boiler",
    why: "WHO recommends 150–300 minutes of moderate activity a week; 150 is the floor, not the ceiling.",
    criterion: { kind: "daily_average", metric: "active_minutes_day", op: ">=", target: 22 },
    windowDays: 7,
    citation: "who2020.activity",
    tags: ["load"],
  },
  {
    id: "engine.easy.1",
    region: "engine",
    stat: "aerobic",
    difficulty: 1,
    evidence: "B",
    title: "Three easy, conversational cardio sessions of 30+ minutes",
    gameTitle: "Engine I: Steady steam",
    why: "Most of an endurance programme should be easy. 'Easy aerobic' is the honest name; no branded intensity band does anything special.",
    criterion: { kind: "sessions", sessionType: "zone2", count: 3, minMinutes: 30 },
    windowDays: 7,
    citation: "aerobic.easy_first",
    tags: ["load"],
  },
  {
    id: "engine.mvpa.2",
    region: "engine",
    stat: "aerobic",
    difficulty: 2,
    evidence: "A",
    title: "Reach 300 active minutes this week",
    gameTitle: "Engine II: Full pressure",
    why: "Benefits keep growing up to about 300 minutes of moderate activity a week, the upper end of the WHO range.",
    criterion: { kind: "daily_average", metric: "active_minutes_day", op: ">=", target: 43 },
    windowDays: 7,
    citation: "who2020.activity",
    tags: ["load"],
  },
  {
    id: "engine.4x4.1",
    region: "engine",
    stat: "aerobic",
    difficulty: 2,
    evidence: "B",
    title:
      "One 4 × 4 interval session (4 min hard, 3 min easy), with 12+ minutes above 85 % of max heart rate",
    gameTitle: "Engine II: Open the throttle",
    why: "4 × 4-minute intervals raised VO₂max more than moderate continuous training in randomised trials; the heart-rate check verifies the hard parts were hard.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "intervals", count: 1, minMinutes: 28 },
        { kind: "days_meeting", metric: "hr_time_above_85pct", op: ">=", threshold: 12, days: 1 },
      ],
    },
    windowDays: 7,
    citation: "aerobic.hiit_vo2max",
    tags: ["load"],
  },
  {
    id: "engine.pyramid.1",
    region: "engine",
    stat: "aerobic",
    difficulty: 2,
    evidence: "B",
    title: "Two easy sessions plus one tempo or interval session",
    gameTitle: "Engine II: Pyramid of steam",
    why: "A pyramidal week, mostly easy with one harder session, matched or beat polarised training in a network meta-analysis.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "zone2", count: 2, minMinutes: 30 },
        { kind: "sessions", sessionType: "intervals", count: 1, minMinutes: 20 },
      ],
    },
    windowDays: 7,
    citation: "aerobic.rosenblat2025",
    tags: ["load"],
  },
  {
    id: "engine.4x4.2",
    region: "engine",
    stat: "aerobic",
    difficulty: 3,
    evidence: "B",
    title: "Two interval sessions plus two easy sessions",
    gameTitle: "Engine III: Twin turbines",
    why: "Two quality sessions a week on an easy base is the dose that moved VO₂max most in trials of healthy adults.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "intervals", count: 2, minMinutes: 28 },
        { kind: "sessions", sessionType: "zone2", count: 2, minMinutes: 30 },
      ],
    },
    windowDays: 7,
    citation: "aerobic.hiit_vo2max",
    tags: ["load"],
  },
  {
    id: "engine.3030.1",
    region: "engine",
    stat: "aerobic",
    difficulty: 3,
    evidence: "C",
    title: "One 30/30 session (30 s hard, 30 s easy, stop when form fades, max 20 reps)",
    gameTitle: "Engine III: Pistons",
    why: "Short alternating intervals keep you near maximal oxygen uptake for longer than one continuous hard effort.",
    criterion: { kind: "sessions", sessionType: "intervals", count: 1, minMinutes: 20 },
    windowDays: 7,
    citation: "aerobic.billat",
    tags: ["load"],
  },
  {
    id: "engine.test.vo2",
    region: "engine",
    stat: "aerobic",
    difficulty: 1,
    evidence: "C",
    title: "Get a fresh device VO₂max estimate (outdoor walk or run)",
    gameTitle: "Engine I: Read the gauge",
    why: "Cardiorespiratory fitness is linked to long-term health in very large cohorts. A device estimate from an outdoor effort reveals your Aerobic stat.",
    criterion: { kind: "measurement_exists", metric: "vo2max", minTrust: 2 },
    windowDays: 14,
    citation: "aerobic.crf_mortality",
    tags: ["test", "import"],
  },
  {
    id: "engine.improve.vo2",
    region: "engine",
    stat: "aerobic",
    difficulty: 3,
    evidence: "B",
    title: "Raise VO₂max by 3 ml/kg/min in 12 weeks",
    gameTitle: "Engine III: A bigger engine",
    why: "Twelve weeks of structured training typically adds a few ml/kg/min; the target sits above device noise, so the change is real.",
    criterion: { kind: "improve", metric: "vo2max", delta: 3 },
    windowDays: 84,
    citation: "aerobic.milanovic2015",
    tags: [],
  },

  // ─── Temple of Motion — mobility ───────────────────────────────────────────────────────────
  {
    id: "temple.stretch.1",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "B",
    title: "Ten minutes of stretching for one tight area, spread over 3+ days",
    gameTitle: "Temple I: Enter the stillness",
    why: "Range of motion improves with about ten minutes of weekly stretching per muscle; gains flatten beyond that.",
    criterion: { kind: "sessions", sessionType: "mobility", count: 3, minMinutes: 3 },
    windowDays: 7,
    citation: "mobility.stretch_dose",
    tags: [],
  },
  {
    id: "temple.fullrom.1",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "B",
    title: "Two full-range strength sessions",
    gameTitle: "Temple I: Strength through the arc",
    why: "Strength training through a full range of motion improves flexibility about as much as stretching does, and counts for the Forge too.",
    criterion: { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 20 },
    windowDays: 7,
    citation: "mobility.afonso2021",
    tags: ["load"],
  },
  {
    id: "temple.test.ktw",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "C",
    title: "Take the knee-to-wall ankle test, both sides",
    gameTitle: "Temple I: Kneel to the wall",
    why: "Ankle range matters for squatting and stairs; about 10 cm is the commonly cited restriction threshold.",
    criterion: { kind: "measurement_exists", metric: "knee_to_wall_cm" },
    windowDays: 14,
    citation: "norms.knee_to_wall",
    tags: ["test"],
  },
  {
    id: "temple.test.reach",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "C",
    title: "Record a sit-and-reach test",
    gameTitle: "Temple I: Reach the floor",
    why: "A simple test for hamstring and lower-back range with published criterion bands.",
    criterion: { kind: "measurement_exists", metric: "sit_and_reach_cm" },
    windowDays: 14,
    citation: "norms.sit_and_reach",
    tags: ["test"],
  },
  {
    id: "temple.warmup.1",
    region: "temple",
    stat: "mobility",
    difficulty: 2,
    evidence: "C",
    title: "Do a dynamic warm-up before 3 workouts (static holds under 60 s)",
    gameTitle: "Temple II: Wake the joints",
    why: "Long static holds right before training can blunt strength and power; short holds and dynamic movement do not.",
    criterion: { kind: "self_report", count: 3 },
    windowDays: 7,
    citation: "mobility.behm2016",
    tags: [],
  },
  {
    id: "temple.stretch.2",
    region: "temple",
    stat: "mobility",
    difficulty: 2,
    evidence: "B",
    title: "Stretch on 5 days, at least 2 minutes each",
    gameTitle: "Temple II: Daily devotion",
    why: "Frequent short sessions improve range of motion as well as fewer long ones; the weekly total is what counts.",
    criterion: { kind: "sessions", sessionType: "mobility", count: 5, minMinutes: 2 },
    windowDays: 7,
    citation: "mobility.thomas2018",
    tags: [],
  },
  {
    id: "temple.improve.sr",
    region: "temple",
    stat: "mobility",
    difficulty: 3,
    evidence: "B",
    title: "Add 3 cm to your sit-and-reach in 6 weeks",
    gameTitle: "Temple III: Past the toes",
    why: "Six weeks of regular stretching reliably adds a few centimetres of reach in trials.",
    criterion: { kind: "improve", metric: "sit_and_reach_cm", delta: 3 },
    windowDays: 42,
    citation: "mobility.dose2024",
    tags: [],
  },
  {
    id: "temple.balance.1",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "A",
    title: "Three balance-and-strength sessions",
    gameTitle: "Temple I: Stand on the stone",
    why: "Balance and functional exercise cut the rate of falls in older adults by about a quarter in Cochrane's review, and WHO recommends it from 65. Everyone can practise balance.",
    criterion: { kind: "sessions", sessionType: "balance", count: 3, minMinutes: 10 },
    windowDays: 7,
    citation: "balance.falls",
    tags: [],
  },
  {
    id: "temple.test.balance",
    region: "temple",
    stat: "mobility",
    difficulty: 1,
    evidence: "C",
    title: "Time a single-leg stance, eyes open",
    gameTitle: "Temple I: One foot on the path",
    why: "Single-leg stance time falls with age in healthy adults and is a quick, repeatable test.",
    criterion: { kind: "measurement_exists", metric: "single_leg_balance_s" },
    windowDays: 14,
    citation: "norms.single_leg_balance",
    tags: ["test"],
  },

  // ─── The Arena — power (region gated on strength and mobility) ─────────────────────────────
  {
    id: "arena.test.jump",
    region: "arena",
    stat: "power",
    difficulty: 1,
    evidence: "C",
    title: "Record a vertical jump",
    gameTitle: "Arena I: Leave the ground",
    why: "Jump height is the simplest field measure of lower-body power, which declines faster than strength with age.",
    criterion: { kind: "measurement_exists", metric: "vertical_jump_cm" },
    windowDays: 14,
    citation: "norms.vertical_jump",
    tags: ["test"],
  },
  {
    id: "arena.test.broad",
    region: "arena",
    stat: "power",
    difficulty: 1,
    evidence: "C",
    title: "Measure a standing broad jump",
    gameTitle: "Arena I: Clear the gap",
    why: "A tape measure is enough. No population norms exist yet, so this tracks your own progress rather than a percentile.",
    criterion: { kind: "measurement_exists", metric: "broad_jump_cm" },
    windowDays: 14,
    citation: "norms.gap.broad_jump",
    tags: ["test"],
  },
  {
    id: "arena.intent.1",
    region: "arena",
    stat: "power",
    difficulty: 1,
    evidence: "C",
    title: "Two strength sessions lifting fast and controlled on the way up",
    gameTitle: "Arena I: Strike with intent",
    why: "Power is linked to everyday function more closely than strength alone; moving loads with intent trains it.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 20 },
        { kind: "self_report", count: 2 },
      ],
    },
    windowDays: 7,
    citation: "power.reid2012",
    tags: ["load"],
  },
  {
    id: "arena.plyo.1",
    region: "arena",
    stat: "power",
    difficulty: 1,
    evidence: "B",
    title: "Two short hop sessions (low, two-footed, 40 contacts or fewer)",
    gameTitle: "Arena I: First bounds",
    why: "Low-amplitude plyometrics improved power and function safely even in older adults when the volume was kept small.",
    criterion: { kind: "sessions", sessionType: "plyometric", count: 2, minMinutes: 10 },
    windowDays: 7,
    citation: "power.plyo_older2019",
    tags: ["load"],
  },
  {
    id: "arena.sts.1",
    region: "arena",
    stat: "power",
    difficulty: 1,
    evidence: "C",
    title: "Add 2 reps to your 30-second sit-to-stand in 4 weeks",
    gameTitle: "Arena I: Rise faster",
    why: "Standing up quickly is lower-body power in everyday clothes; the chair-stand count is the most practical marker after 60.",
    criterion: { kind: "improve", metric: "sit_to_stand_30s", delta: 2 },
    windowDays: 28,
    citation: "power.older_adults",
    tags: [],
    minAge: 60,
  },
  {
    id: "arena.plyo.2",
    region: "arena",
    stat: "power",
    difficulty: 2,
    evidence: "B",
    title: "Two jump sessions (box or broad jumps, full recovery between efforts)",
    gameTitle: "Arena II: Higher bounds",
    why: "Progressing from hops to jumps with full rest builds power without turning the session into conditioning.",
    criterion: { kind: "sessions", sessionType: "plyometric", count: 2, minMinutes: 15 },
    windowDays: 7,
    citation: "power.plyo_older2019",
    tags: ["load"],
  },
  {
    id: "arena.sprint.1",
    region: "arena",
    stat: "power",
    difficulty: 2,
    evidence: "D",
    title: "One hill-sprint session (6–8 × 10 s, walk back down)",
    gameTitle: "Arena II: Charge the slope",
    why: "Early research suggests short hill sprints train power with less impact than flat sprints. This exact protocol is a design choice, not a tested one.",
    criterion: { kind: "sessions", sessionType: "sprint", count: 1, minMinutes: 15 },
    windowDays: 7,
    citation: "design.hill_sprints",
    tags: ["load", "opt_in"],
  },
  {
    id: "arena.improve.jump",
    region: "arena",
    stat: "power",
    difficulty: 3,
    evidence: "C",
    title: "Add 5 cm to your broad jump in 6 weeks",
    gameTitle: "Arena III: Clear a wider gap",
    why: "Six weeks of jump training moves broad-jump distance by a few centimetres in most trials.",
    criterion: { kind: "improve", metric: "broad_jump_cm", delta: 5 },
    windowDays: 42,
    citation: "power.plyo_older2019",
    tags: [],
  },
  {
    id: "arena.test.sprint",
    region: "arena",
    stat: "power",
    difficulty: 2,
    evidence: "D",
    title: "Time a 10 m sprint",
    gameTitle: "Arena II: Ten metres of thunder",
    why: "Phone timing has not been validated against gates and no adult norms exist, so this is a personal benchmark only.",
    criterion: { kind: "measurement_exists", metric: "sprint_10m_s" },
    windowDays: 14,
    citation: "norms.gap.sprint",
    tags: ["test"],
  },

  // ─── The Wilds — movement ──────────────────────────────────────────────────────────────────
  {
    id: "wilds.import.steps",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "B",
    title: "Connect a step counter (phone or watch)",
    gameTitle: "Wilds I: Leave footprints",
    why: "Daily steps are the best-measured marker of everyday movement; a device-recorded week reveals your Movement stat.",
    criterion: { kind: "measurement_exists", metric: "steps_day", minTrust: 2 },
    windowDays: 14,
    citation: "steps.dose_response",
    tags: ["import"],
  },
  {
    id: "wilds.steps.up",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "B",
    title: "Average 1,000 more steps a day than your last 4 weeks",
    gameTitle: "Wilds I: One more ridge",
    why: "Each extra thousand steps a day is linked to lower risk across many outcomes; the biggest gains come from the first few thousand.",
    criterion: { kind: "improve_mean", metric: "steps_day", delta: 1000, baselineDays: 28 },
    windowDays: 7,
    citation: "steps.ding2025",
    tags: [],
  },
  {
    id: "wilds.steps.1",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "B",
    title: "Average 7,000 steps a day",
    gameTitle: "Wilds I: Find your stride",
    why: "Mortality risk falls steeply up to roughly 7,000–8,000 steps a day; the first thousands matter most.",
    criterion: { kind: "daily_average", metric: "steps_day", op: ">=", target: 7000 },
    windowDays: 7,
    citation: "steps.dose_response",
    tags: [],
  },
  {
    id: "wilds.steps.2",
    region: "wilds",
    stat: "movement",
    difficulty: 2,
    evidence: "B",
    title: "Average 9,000 steps a day",
    gameTitle: "Wilds II: Longer paths",
    why: "Benefits keep accruing into the 8,000–10,000 range for adults under 60.",
    criterion: { kind: "daily_average", metric: "steps_day", op: ">=", target: 9000 },
    windowDays: 7,
    citation: "steps.paluch2022",
    tags: [],
    maxAge: 59,
  },
  {
    id: "wilds.steps.2.60plus",
    region: "wilds",
    stat: "movement",
    difficulty: 2,
    evidence: "B",
    title: "Average 8,000 steps a day",
    gameTitle: "Wilds II: Longer paths",
    why: "From 60 on, the dose-response curve flattens around 6,000–8,000 steps a day; 8,000 sits at the top of it.",
    criterion: { kind: "daily_average", metric: "steps_day", op: ">=", target: 8000 },
    windowDays: 7,
    citation: "steps.paluch2022",
    tags: [],
    minAge: 60,
  },
  {
    id: "wilds.breaks.1",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "B",
    title: "Break up sitting 8+ times on 5 days",
    gameTitle: "Wilds I: Never still",
    why: "Interrupting prolonged sitting with short walks lowered post-meal glucose and insulin in a crossover trial.",
    criterion: { kind: "days_meeting", metric: "sedentary_break_count_day", op: ">=", threshold: 8, days: 5 },
    windowDays: 7,
    citation: "sedentary.dunstan2012",
    tags: [],
  },
  {
    id: "wilds.vilpa.1",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "C",
    title: "Three one-minute vigorous bursts (stairs, fast uphill walk) on 5 days",
    gameTitle: "Wilds I: Sprint between the trees",
    why: "A few minutes a day of vigorous incidental activity is linked to lower mortality in people who do no structured exercise.",
    criterion: { kind: "days_meeting", metric: "vilpa_bouts_day", op: ">=", threshold: 3, days: 5 },
    windowDays: 7,
    citation: "vilpa.stamatakis",
    tags: [],
  },
  {
    id: "wilds.brisk.1",
    region: "wilds",
    stat: "movement",
    difficulty: 1,
    evidence: "A",
    title: "Three brisk walks of 20+ minutes",
    gameTitle: "Wilds I: Walk the long road",
    why: "Brisk walking is moderate activity, the kind WHO recommends 150–300 minutes of each week.",
    criterion: { kind: "sessions", sessionType: "walk", count: 3, minMinutes: 20 },
    windowDays: 7,
    citation: "who2020.activity",
    tags: [],
  },
  {
    id: "wilds.vilpa.2",
    region: "wilds",
    stat: "movement",
    difficulty: 2,
    evidence: "C",
    title: "Five vigorous bursts a day on 5 days",
    gameTitle: "Wilds II: The quick way through",
    why: "More bursts were linked to lower risk than fewer in the wearable cohorts; the curve had not flattened at five.",
    criterion: { kind: "days_meeting", metric: "vilpa_bouts_day", op: ">=", threshold: 5, days: 5 },
    windowDays: 7,
    citation: "vilpa.stamatakis",
    tags: [],
  },

  // ─── The Garden — nutrition, additive by default ───────────────────────────────────────────
  {
    id: "garden.log.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 1,
    evidence: "C",
    title: "Log your meals on 3 days",
    gameTitle: "Garden I: Walk the beds",
    why: "Three logged days are enough to see where fibre, protein and plants stand against the targets. Self-logged food data is approximate.",
    criterion: { kind: "days_meeting", metric: "fiber_g_day", op: ">=", threshold: 0, days: 3 },
    windowDays: 7,
    citation: "design.food_log",
    tags: ["test"],
  },
  {
    id: "garden.fiber.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 1,
    evidence: "B",
    title: "Eat 25+ g of fibre on 4 days",
    gameTitle: "Garden I: Let it grow",
    why: "Intakes of 25–29 g of fibre a day were associated with lower risk across many outcomes in a Lancet review of trials and cohorts.",
    criterion: { kind: "days_meeting", metric: "fiber_g_day", op: ">=", threshold: 25, days: 4 },
    windowDays: 7,
    citation: "fiber.reynolds2019",
    tags: ["additive_nutrition"],
  },
  {
    id: "garden.plants.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 1,
    evidence: "B",
    title: "Eat 5+ servings of plants on 5 days",
    gameTitle: "Garden I: Five seeds a day",
    why: "Diets rich in vegetables, fruit, legumes and whole grains lowered cardiovascular events in the republished PREDIMED trial and large cohorts.",
    criterion: { kind: "days_meeting", metric: "plant_servings_day", op: ">=", threshold: 5, days: 5 },
    windowDays: 7,
    citation: "plants.reynolds_predimed",
    tags: ["additive_nutrition"],
  },
  {
    id: "garden.protein.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 2,
    evidence: "B",
    title: "Hit 1.6 g/kg protein on 5 days",
    gameTitle: "Garden II: Feed the roots",
    why: "Lean-mass gains from resistance training plateau around 1.6 g/kg/day of protein; more adds little.",
    criterion: { kind: "days_meeting", metric: "protein_g_per_kg_day", op: ">=", threshold: 1.6, days: 5 },
    windowDays: 7,
    citation: "protein.morton2018",
    tags: ["additive_nutrition"],
  },
  {
    id: "garden.protein.2",
    region: "garden",
    stat: "nutrition",
    difficulty: 2,
    evidence: "C",
    title: "Three meals with 0.4+ g/kg protein on 4 days",
    gameTitle: "Garden II: Spread the seed",
    why: "Spreading protein over several meals of about 0.4 g/kg each is the practical way to reach a daily total.",
    criterion: { kind: "days_meeting", metric: "protein_meals_day", op: ">=", threshold: 3, days: 4 },
    windowDays: 7,
    citation: "protein.schoenfeld2018",
    tags: ["additive_nutrition"],
  },
  {
    id: "garden.cook.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 2,
    evidence: "B",
    title: "Cook 5 meals from minimally processed ingredients",
    gameTitle: "Garden II: From the soil",
    why: "In a controlled feeding trial, people ate about 500 kcal a day more on an ultra-processed diet than on a matched unprocessed one.",
    criterion: { kind: "self_report", count: 5 },
    windowDays: 7,
    citation: "upf.hall2019",
    tags: ["additive_nutrition"],
  },
  {
    id: "garden.alcohol.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 2,
    evidence: "A",
    title: "Five alcohol-free days",
    gameTitle: "Garden II: Clear water",
    why: "WHO and the German Nutrition Society state that no level of alcohol is safe for health. You choose this quest; it is never assigned.",
    criterion: { kind: "days_meeting", metric: "alcohol_drinks_day", op: "<=", threshold: 0, days: 5 },
    windowDays: 7,
    citation: "alcohol.no_safe_level",
    tags: ["opt_in"],
  },
  {
    id: "garden.creatine.1",
    region: "garden",
    stat: "nutrition",
    difficulty: 2,
    evidence: "B",
    title: "Take 3–5 g of creatine on 5 days",
    gameTitle: "Garden II: The one true tonic",
    why: "Creatine monohydrate is the best-supported supplement for strength and muscle in healthy adults, per the ISSN position stand. Opt-in only.",
    criterion: { kind: "self_report", count: 5 },
    windowDays: 7,
    citation: "creatine.issn2017",
    tags: ["additive_nutrition", "opt_in"],
    minAge: 18,
  },
  {
    id: "garden.fiber.2",
    region: "garden",
    stat: "nutrition",
    difficulty: 3,
    evidence: "B",
    title: "Average 30+ g of fibre a day",
    gameTitle: "Garden III: Deep roots",
    why: "The Lancet review's dose-response kept improving up to about 30 g a day and beyond.",
    criterion: { kind: "daily_average", metric: "fiber_g_day", op: ">=", target: 30 },
    windowDays: 7,
    citation: "fiber.reynolds2019",
    tags: ["additive_nutrition"],
  },

  // ─── The Sanctum — recovery ────────────────────────────────────────────────────────────────
  {
    id: "sanctum.sleep.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 1,
    evidence: "A",
    title: "Sleep 7+ hours on 5 nights",
    gameTitle: "Sanctum I: Keep the vigil",
    why: "Sleep medicine bodies recommend that adults regularly sleep seven or more hours a night.",
    criterion: { kind: "days_meeting", metric: "sleep_duration_h", op: ">=", threshold: 7, days: 5 },
    windowDays: 7,
    citation: "sleep.consensus_7h",
    tags: ["recovery"],
  },
  {
    id: "sanctum.regular.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 1,
    evidence: "C",
    title: "Wake within 30 minutes of your target on 5 days",
    gameTitle: "Sanctum I: Same hour, same door",
    why: "Sleep regularity predicted mortality risk more strongly than sleep duration in a large UK cohort; a fixed wake time is the easiest lever.",
    criterion: { kind: "days_meeting", metric: "wake_deviation_min", op: "<=", threshold: 30, days: 5 },
    windowDays: 7,
    citation: "sleep.windred2024",
    tags: ["recovery"],
  },
  {
    id: "sanctum.regular.2",
    region: "sanctum",
    stat: "recovery",
    difficulty: 2,
    evidence: "C",
    title: "Keep your Sleep Regularity Index at 80+ over two weeks",
    gameTitle: "Sanctum II: The steady flame",
    why: "Regular sleepers had the lowest risk in the cohort data; the index needs two weeks of nights to mean anything.",
    criterion: { kind: "daily_average", metric: "sleep_regularity_index", op: ">=", target: 80 },
    windowDays: 14,
    citation: "sleep.windred2024.sri80",
    tags: ["recovery"],
  },
  {
    id: "sanctum.extend.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 2,
    evidence: "D",
    title: "Sleep 30 minutes more on average than your last 4 weeks",
    gameTitle: "Sanctum II: Lengthen the night",
    why: "Early research suggests extending sleep improves performance and mood; the key study was tiny, so this may not apply to you.",
    criterion: { kind: "improve_mean", metric: "sleep_duration_h", delta: 0.5, baselineDays: 28 },
    windowDays: 7,
    citation: "sleep.mah2011",
    tags: ["recovery"],
  },
  {
    id: "sanctum.dry.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 1,
    evidence: "B",
    title: "Five alcohol-free evenings; watch what your HRV does",
    gameTitle: "Sanctum I: Still waters",
    why: "Even moderate alcohol lowered heart-rate variability and raised heart rate during the first hours of sleep in a large wearable study.",
    criterion: { kind: "self_report", count: 5 },
    windowDays: 7,
    citation: "alcohol.hrv.pietila2018",
    tags: ["recovery", "opt_in"],
  },
  {
    id: "sanctum.hrv.base",
    region: "sanctum",
    stat: "recovery",
    difficulty: 1,
    evidence: "C",
    title: "Wear your device for 14 nights to build an HRV baseline",
    gameTitle: "Sanctum I: Learn your own pulse",
    why: "HRV only means something against your own baseline; there are no valid population norms, so two weeks of nights come first.",
    criterion: { kind: "days_meeting", metric: "hrv_rmssd", op: ">=", threshold: 0, days: 14 },
    windowDays: 14,
    citation: "hrv.personal_baseline",
    tags: ["recovery", "import"],
  },
  {
    id: "sanctum.sauna.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 2,
    evidence: "C",
    title: "Two sauna sessions of 10+ minutes",
    gameTitle: "Sanctum II: The hot stones",
    why: "Frequent sauna bathing was linked to lower cardiovascular mortality in a Finnish cohort. An association, not a demonstrated cause.",
    criterion: { kind: "sessions", sessionType: "sauna", count: 2, minMinutes: 10 },
    windowDays: 7,
    citation: "sauna.laukkanen2015",
    tags: ["recovery", "opt_in"],
  },
  {
    id: "sanctum.rest.1",
    region: "sanctum",
    stat: "recovery",
    difficulty: 1,
    evidence: "D",
    title: "Take at least one full rest day",
    gameTitle: "Sanctum I: Lay down the hammer",
    why: "A planned week off did not reduce muscle gains in a small trial, and coaches agree on regular deloads. A rest day costs nothing.",
    criterion: { kind: "rest_days", days: 1 },
    windowDays: 7,
    citation: "strength.deload",
    tags: ["recovery"],
  },

  // ─── The Summit — hybrid (region gated on level and all stats) ─────────────────────────────
  {
    id: "summit.base.1",
    region: "summit",
    stat: "strength",
    difficulty: 1,
    evidence: "A",
    title: "Two strength sessions plus 150 active minutes",
    gameTitle: "Summit I: Base camp",
    why: "Both halves of the WHO recommendation in one week; doing both is linked to lower mortality than either alone.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 20 },
        { kind: "daily_average", metric: "active_minutes_day", op: ">=", target: 22 },
      ],
    },
    windowDays: 7,
    citation: "who2020.activity",
    tags: ["load"],
  },
  {
    id: "summit.week.2",
    region: "summit",
    stat: "aerobic",
    difficulty: 2,
    evidence: "B",
    title: "Two strength, one interval and two easy sessions",
    gameTitle: "Summit II: The ascent",
    why: "A balanced training week: enough strength volume to grow, one hard aerobic session, and an easy base.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "resistance", count: 2, minMinutes: 20 },
        { kind: "sessions", sessionType: "intervals", count: 1, minMinutes: 20 },
        { kind: "sessions", sessionType: "zone2", count: 2, minMinutes: 30 },
      ],
    },
    windowDays: 7,
    citation: "aerobic.easy_first",
    tags: ["load"],
  },
  {
    id: "summit.week.3",
    region: "summit",
    stat: "strength",
    difficulty: 3,
    evidence: "B",
    title: "Three strength, two interval and two easy sessions",
    gameTitle: "Summit III: The ridge",
    why: "Seven sessions is a serious week; the dose data support it for people who already train, and recovery decides whether it sticks.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "sessions", sessionType: "resistance", count: 3, minMinutes: 30 },
        { kind: "sessions", sessionType: "intervals", count: 2, minMinutes: 28 },
        { kind: "sessions", sessionType: "zone2", count: 2, minMinutes: 30 },
      ],
    },
    windowDays: 7,
    citation: "aerobic.hiit_vo2max",
    tags: ["load"],
  },
  {
    id: "summit.retest.1",
    region: "summit",
    stat: "aerobic",
    difficulty: 1,
    evidence: "C",
    title: "Retest VO₂max, push-ups and sit-and-reach",
    gameTitle: "Summit I: Survey the peaks",
    why: "A fresh set of tests moves the sheet from old numbers to current ones across three stats at once.",
    criterion: {
      kind: "all_of",
      parts: [
        { kind: "measurement_exists", metric: "vo2max" },
        { kind: "measurement_exists", metric: "pushups_max" },
        { kind: "measurement_exists", metric: "sit_and_reach_cm" },
      ],
    },
    windowDays: 14,
    citation: "norms.vo2max",
    tags: ["test"],
  },
];

export const QUEST_TEMPLATES: readonly QuestTemplate[] = TEMPLATES;

export function templateById(id: string): QuestTemplate | undefined {
  return QUEST_TEMPLATES.find((t) => t.id === id);
}

export function citationFor(t: QuestTemplate): CitationRef | undefined {
  return (CITATIONS as Record<string, CitationRef>)[t.citation];
}
